app/globals.css
tailwind.config.ts

어떤 변경 사항이 있나요?
- 컬러값이 기본으로 hsl로 되어있는걸 헥사코드로 변경했습니다.
- 커스텀 색상을 추가 했습니다.

:lipstick:Style : 컬러값 hsl -> 헥사, 커스텀 색상 추가

---

app/globals.css
tailwind.config.ts

💄Style : 커스텀 색상 추가

---

app/(main)/mydiary/diary.tsx
lib/function/get-emotion-classes.ts

:sparkles:Feat : 클래스값 불러오는 로직 함수화 (#27)

---

components/dropdown.tsx
components/ui/dropdown-menu.tsx
package-lock.json
package.json

💄 diary 컴포넌트 드롭다운 메뉴 추가

---

app/(main)/mydiary/diary.tsx
app/(main)/mydiary/page.tsx
app/globals.css
components/dropdown.tsx

어떤 변경 사항이 있나요?
- 드롭다운 메뉴 diary 컴포넌트에 추가 

:lipstick:Style : 드롭다운 메뉴 추가 및 네비게이션 헤더 추가 (#29)

---

app/(main)/mydiary/diary.tsx
lib/function/get-emotion-classes.ts

🐛 Modify 다이어리 컴포넌트 구조 수정 및 getEmoitionClasses 로직 수정

---

app/(main)/mydiary/diary.tsx
lib/function/get-info-by-mood.ts

:sparkles:Feat : getInfoByMood 함수 구현 (#34)

---

app/(main)/mydiary/page.tsx

:sparkes:Feat : 마이다이어리 페이지 구현 (#34)

---

app/(main)/mydiary/diary.tsx
app/(main)/mydiary/page.tsx
lib/function/get-emotion-classes.ts
lib/function/get-info-by-mood.ts

:lipstick:Style : mydiary page 및 diary component 스타일 수정 (#44)

---

app/(main)/mydiary/diary.tsx
lib/function/get-txtcolor-classes.ts
tailwind.config.ts

:lipstick:Style : diary component css 수정 (#44)

---

app/(onboarding)/get-extra-user-info/multi-select/[process]/page.tsx
app/(onboarding)/get-extra-user-info/process-status-green.tsx
app/(onboarding)/get-extra-user-info/radio/[process]/page.tsx
app/(onboarding)/get-extra-user-info/select/[process]/page.tsx
app/(onboarding)/onboarding/page.tsx
components/tag.tsx
hooks/store/use-user-data.tsx

✨ Feat : 유저 추가 정보를 전역 상태 값에 저장. multi-select 관심사 선택 페이지 UI 작성 및 스타일링. 오류 해결.

---

app/(main)/mydiary/[id]/page.tsx
app/(main)/mydiary/[id]/write-diary/emotion-item.tsx
app/(main)/mydiary/[id]/write-diary/page.tsx
app/(main)/mydiary/write-diary-btn.tsx
components/diary.tsx
lib/function/get-img-by-mood.ts
lib/function/get-txt-by-mood.ts

어떤 변경 사항이 있나요?
- mydiary 폴더구조 수정 
- 글작성 UI 추가
- 공용 함수 경로 수정
- 

✨ mydiary 폴더구조 수정 및 글작성 UI 추가

---

lib/protocol.ts
types/api-response.ts
types/exchange-diary.ts
types/jwt.ts
types/my-diarys.ts
types/user.ts

✨ Feat 각 entity 별 타입 및 Respone 타입 추가 및 protocal 모듈 headers client-id 추가

---

app/(main)/mydiary/write-diary2/page.tsx
app/layout.tsx
app/page.tsx
hooks/store/use-diary.tsx

✨ 전역변수 selectedTags 타입 변경에 따른 로직 변경

---

app/(main)/mydiary/page.tsx
components/diary.tsx
lib/function.ts
types/my-diarys.ts

✨ post DB(내 일기 데이터)에서 title 속성 extra 속성 안으로 이동

---

app/(main)/mydiary/edit-diary/page.tsx
app/(main)/mydiary/write-diary/emotion-item.tsx
app/(main)/mydiary/write-diary/page.tsx
app/(main)/mydiary/write-diary2/page.tsx
components/dropdown.tsx
components/navigation-header.tsx
hooks/store/use-diary.tsx
lib/function.ts

✨ 일기 수정 페이지 기능구현 및 UI 수정 (#86)

---

app/(main)/_components/exchange-diary.tsx
app/(main)/exchange-diary/delivery-status-item.tsx
components/ui/progress.tsx
hooks/mutation/product.ts

✨ Feat 교환일기 프로그레스바 수정

---

app/layout.tsx
lib/protocol.ts
provider/auth-provider.tsx

✨ Feat : 요청시 헤더에 토큰 담기는 로직 추가

---

hooks/mutation/deletePost.ts
hooks/mutation/patchPost.ts

:sparkles:Feat : 일기 API(수정,삭제) 훅 추가

---

app/(main)/mydiary/page.tsx
components/diary.tsx

:lipstick:Style : mydiary 페이지, diary 컴포넌트 css 수정

---

hooks/store/use-diary.tsx

:pencil2:Modify : _id 속성 필수로 설정

---

types/my-diarys.ts

:pencil2:Modify : content 속성 extra 속성 내부로 이동

---

app/(main)/_components/exchange-diary.tsx
hooks/mutation/product.ts
lib/protocol.ts

:sparkels:Feat : build 에러 해결 및 accessToken 접근 시점 서버->클라이언트로 수정

---

app/(main)/mypage/page.tsx
app/(main)/mypage/switch-item.tsx
app/api/signup/route.ts

✨ Feat 내 정보 페이지에 로그아웃 버튼 및 기능 추가, signup route handler에 있는 redirect 경로 수정.

---

app/(main)/mydiary/page.tsx

🐛 Modify mydiary 페이지에 argument 추가해서 빌드 에러 해결

---

app/layout.tsx

🐛 Modify iOS 모바일 환경에서 스플래시 이미지가 뜨지 않는 문제 해결

---

app/(main)/mydiary/write-diary/data-preview.tsx
app/(main)/mydiary/write-diary/note.tsx
app/(main)/mydiary/write-diary/page.tsx
app/(main)/mydiary/write-diary/tab-datas.tsx
app/(main)/mydiary/write-diary/tabs.tsx
app/(main)/mydiary/write-note/page.tsx
hooks/store/use-diary.tsx
provider/auth-provider.tsx

:recycle:Refactor : 코드 컴포넌트로 분리 (#126)

---

middleware.ts

✨Feat welcome 페이지 최초 접속 이후 로그인 한 사용자가 url을 이용해 welcome 페이지에 접속하지 못하도록 설정

---

app/(onboarding)/welcome/page.tsx
app/layout.tsx
hooks/use-current-session.tsx
hooks/use-user.tsx
provider/auth-provider.tsx
provider/fcm-provider.tsx

🐛 Modify useSession을 사용한 session 불러오기가 강제 새로고침 해야만 작동하던 문제 해결

---

app/(main)/exchange-diary/send-diary-tab.tsx
app/api/fcm/route.ts
components/interest-bottom-sheet.tsx
hooks/mutation/product.tsx
hooks/query/products.tsx
hooks/use-send-push.tsx
lib/firebase.ts
provider/auth-provider.tsx
provider/fcm-provider.tsx
public/firebase-messaging-sw.js

🐛 Bug : 버그 수정

---

app/(main)/exchange-diary/(no-layout)/load-diary/page.tsx
app/(main)/mydiary/page.tsx
app/layout.tsx
components/navigation-header.tsx

어떤 변경 사항이 있나요?
- load-diary 페이지에서 내가 작성한 일기만 불러오게 수정
- SessionProvider layout에 다시 추가 useCurrentSession훅에서 getSession() 사용하려면 필요함
- 

✨ Feat : load-diary 페이지에서 내가 작성한 일기만 불러오게 수정

---

lib/function.ts

✏️ convertTime 중복 제거

---

components/navigation-header.tsx

✏️ navigation-header 뒤로가기버튼 중복제거

---

app/(main)/exchange-diary/exchange-diary-tab.tsx
hooks/use-send-push.tsx
lib/firebase.ts
provider/fcm-provider.tsx

🐛 Bug : 네비게이터 수정

---

app/(main)/exchange-diary/exchange-diary-tab.tsx

🐛 Bug : import Error 수정

---

hooks/use-send-push.tsx
provider/fcm-provider.tsx

🐛 배포 버그 수정

---

hooks/use-send-push.tsx

🐛 배포 에러 수정

---

app/(main)/exchange-diary/(no-layout)/load-diary/page.tsx
app/(main)/mydiary/page.tsx
components/dropdown.tsx
components/navigation-header.tsx
hooks/query/post.tsx

어떤 변경 사항이 있나요?
```ts
export const usePostsMyDiarys = (type: string, userId: number) => {
const searchParams = new URLSearchParams()
searchParams.append("custom", JSON.stringify({ "user._id": userId }))
const { data, isPending, error, refetch } = useQuery<
Record<string, DiaryTypes[]> | undefined
>({
queryKey: [apiKeys.posts, userId],
queryFn: async () => {
const res = await fetcher(
`${apiKeys.posts}?type=${type}&${searchParams.toString()}`
)
// 빈값일때 undefined를 리턴해줘서 발생한 에러, 빈값일때 {} 빈 객체 리턴해야함
// if (res && res.item.length === 0) {
//   return undefined
// }
return sortMyDiarys(res.item)
},
})
return {
data,
isPending,
error,
refetch,
}
}
```

🐛 내일기 삭제 에러 해결

---

middleware.ts

✨ Feat 로그인 한 상태일 때 접속이 방지되어야 하는 페이지들에 접속 방지 기능 추가

---

app/(main)/mypage/switch-item.tsx
components/footer.tsx
middleware.ts

💄 Modify QA 후 스타일 수정

---

app/(main)/mypage/switch-item.tsx
app/api/oauth-signup/route.ts

🐛 Modify oauth로 로그인 한 사용자의 일기 작성 및 교환이 제대로 작동하지 않는 문제 해결

---

app/(main)/exchange-diary/(no-layout)/load-diary/page.tsx
app/(main)/exchange-diary/(no-layout)/preview/[id]/page.tsx
app/(main)/exchange-diary/(no-layout)/storage/[id]/page.tsx
app/(main)/exchange-diary/delivery-status-item.tsx
app/(main)/exchange-diary/send-diary-tab.tsx
hooks/mutation/product.tsx
hooks/query/post.tsx
hooks/query/products.tsx
lib/function.ts
types/exchange-diary.ts

🐛 교환일기 리팩토링 및 UI 수정

---

components/interest-bottom-sheet.tsx

🐛  Modify type 에러 해결

---

app/(main)/mypage/switch-item.tsx

🐛 Modify 로그아웃이 유지되지 않는 문제 해결

---

components/interest-bottom-sheet.tsx
hooks/mutation/product.tsx
hooks/query/post.tsx
hooks/use-user.tsx

🐛 Modify 교환일기 버그 추가 작업 타겟유저가 없을시 리턴 및 기타 벨리데이션 추가

---

app/(main)/exchange-diary/(no-layout)/storage/[id]/page.tsx
app/(main)/exchange-diary/diary-storage-tab.tsx
app/(main)/exchange-diary/send-diary-tab.tsx
hooks/store/use-target.tsx

🐛 Fix : 교환일기 발송시 대상에게 일기가 안쌓이는 버그 수정

---

app/(main)/mypage/switch-item.tsx
app/page.tsx

🐛 Modify 로그아웃이 제대로 작동하지 않는 버그 수정

---

app/(main)/mypage/switch-item.tsx
app/page.tsx

🐛 Modify 로그아웃이 정상적으로 작동하지 않는 버그 수정

---

app/(main)/mypage/switch-item.tsx

🐛 Modify 로그아웃 문제 해결

---

app/(main)/mypage/switch-item.tsx

🐛 Modify 로그아웃 문제 해결 시도

---

app/(main)/exchange-diary/(layout)/page.tsx
app/(main)/exchange-diary/(layout)/tabs-container.tsx
app/(main)/exchange-diary/(no-layout)/load-diary/page.tsx
app/(main)/exchange-diary/(no-layout)/load-diary/render-load-diary.tsx
app/(main)/exchange-diary/diary-storage-tab.tsx
app/(main)/mydiary/components/render-mydiary.tsx
app/(main)/mydiary/page.tsx
components/spinner.tsx
hooks/query/products.tsx

🐛 Modify 내 일기 페이지, 교환 일기 페이지에 부분 로딩 UI 추가 및 refetch 로직 제거 

---

actions/userAction.ts
app/(onboarding)/(auth)/signup/page.tsx
app/auth.ts
components/avatar-name.tsx
lib/protocol.ts
types/user.ts

✨Feat 프로필 이미지 표시 기능 추가

---

app/page.tsx

✨ Feat 이미 가입한 회원일 경우 랜딩 페이지에서 바로 로그인 페이지로 갈 수 있도록 링크 추가

---

components/interest-bottom-sheet.tsx
components/tag.tsx

:bug:Modify : interest-bottom-sheet, pathName으로 분기처리

---

actions/authAction.ts
actions/updateSessionAction.ts
app/(main)/mypage/page.tsx
app/api/oauth-signup/route.ts
app/auth.ts
auth.d.ts
components/interest-bottom-sheet.tsx
middleware.ts
package-lock.json
package.json
provider/auth-provider.tsx

✨Feat 액세스 토큰 만료 시 리프레시 토큰으로 재발급, 리프레시 토큰 만료 시 자동 로그아웃되어 로그인 페이지로 리다이렉션 되도록 기능 추가,  사용자의 관심사를 등록하거나 수정하면 session의 interest 값이 업데이트 되도록 수정, 불필요한 코드 삭제

---

actions/authAction.ts
app/(onboarding)/(auth)/login/page.tsx
app/(onboarding)/(auth)/signup/page.tsx
app/api/credentials-login/route.ts
app/api/oauth-signup/route.ts
types/user.ts

🐛 Modify 일반 로그인 시 리프레시 토큰 재발급이 정상적으로 발급되지 않는 문제 수정, 프로필 이미지를 등록하지 않으면 db에 저장되지 않던 것을 null 값으로 저장되도록 수정

---

app/auth.ts
auth.d.ts
provider/auth-provider.tsx

♻️ Refactor 리프레시 토큰 만료 판단 플래그 변수명을 더 명확하게 변경

---

app/(main)/mydiary/components/empty-diary.tsx
app/(main)/mydiary/components/render-mydiary.tsx
app/(main)/mydiary/data.tsx
app/(main)/mydiary/write-diary-btn.tsx

🐛Modify : 일기 작성 후, mydiary 페이지가 아닌 다른 페이지를 잠시 보여주던 버그 해결

---

provider/auth-provider.tsx

✨ Feat 리프레시 토큰이 만료되었을 때 alert 메세지가 뜨도록 추가

---

app/(main)/mydiary/new/write-diary/diary-step.tsx
app/(main)/mydiary/page.tsx
components/diary.tsx
types/my-diarys.ts

카메라 촬영 및 갤러리에서 이미지 불러오는 기능 / 상황별 태그들 컴포넌트에 제스쳐 기능 / 내일기에 이미지 랜더링 기능 추가 

---

components/interest-bottom-sheet.tsx
components/tag.tsx

🐛Modify : build warnning에러 해결

---

app/(main)/mydiary/new/write-diary/diary-step.tsx
app/(main)/mydiary/page.tsx
components/interest-bottom-sheet.tsx
hooks/use-user.tsx
next.config.mjs

🐛 Modify : build 에러 해결

---

app/(main)/mydiary/[diaryId]/edit-diary/page.tsx
app/(main)/mydiary/[diaryId]/write-note/page.tsx
app/(main)/mydiary/components/render-mydiary.tsx
app/(main)/mydiary/new/write-diary/diary-step.tsx
app/(main)/mydiary/new/write-note/page.tsx
app/(main)/mydiary/page.tsx
components/navigation-header.tsx
hooks/query/post.tsx

✨  날짜 변경시 해당하는 날짜의 일기로 이동하는 기능 추가 /  업로드한 이미지 수정 기능 추가

---

app/(main)/mydiary/new/write-diary/diary-step.tsx

✨Feat : 글 저장시 변수 초기화 기능 추가 및 수정
